// import '../styles/globals.css'
import '../styles/public.css'
import type { AppProps } from 'next/app'
import Header from '../src/components/Header/header'
import Head from "next/head";
// import styles from '../styles/Home.module.css'

export default function App({ Component, pageProps }: AppProps) {
  return (
      <div>
          <Head>
              <title>전오승</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
          <Header />
          <div>
              <Component {...pageProps}/>
          </div>
      </div>
  )
}