import '../styles/public.css'
import type { AppProps } from 'next/app'
import Header from '../src/components/Header/header'
import Head from "next/head";
import {Provider} from "react-redux";
import store from "../store/store";

export default function App({ Component, pageProps }: AppProps) {

  return (
      <div>
          <Head>
              <title>전오승</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
          <Header />
          <Provider store={store}>
              <Component {...pageProps}/>
          </Provider>
      </div>
  )
}