import '../styles/public.css'
import type { AppProps } from 'next/app'
import Header from '../src/components/Header/header'
import Head from "next/head";
import {Provider} from "react-redux";
import store from "../store/store";
import {QueryClient, QueryClientProvider, Hydrate, useQuery, dehydrate} from "react-query";
import {ReactQueryDevtools} from "react-query/devtools";
import {getSession} from "../src/components/Get/api";

interface props extends AppProps{
    user:any
}
export default function App({Component, pageProps, user}: props) {
    const query = new QueryClient();
    return (
        <div>
            <Head>
                <title>전오승</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <QueryClientProvider client={query}>
                <Hydrate state={pageProps.dehydratedState}>
                    <Provider store={store}>
                        <Header />
                        <Component {...pageProps}/>
                    </Provider>
                </Hydrate>
                <ReactQueryDevtools initialIsOpen={false} position='bottom-right' />
            </QueryClientProvider>
        </div>
    )
}
export async function getServerSideProps(){
    const queryClient = new QueryClient()
    await queryClient.prefetchQuery('user',getSession)

    return {
        props:{
            dehydratedState: dehydrate(queryClient),
        }
    }
}
